### ISSUE TITLE
srs_reverse sometimes fails to rewrite SRS1 multihop addresses

### ISSUE THREAD

**Issue by philkernick** [roehling/postsrsd#100]
Examples:
```
<srs1=7g4y=6ppn=3g=brokersunion.org=a.maldini@rotfl.com.au> rewritten as <SRS03g=brokersunion.org=a.maldini@6ppn>
<srs1=rtva=wxbs=3g=notifications.pinterest.com=bounces-420312715131717559@rotfl.com.au> rewritten as <SRS03g=notifications.pinterest.com=bounces-420312715131717559@wxbs>
<SRS1=ZrPg=5KPL=3G=insideapple.apple.com=newsdigest_i_bounces@rotfl.com.au> rewritten as <SRS03G=insideapple.apple.com=newsdigest_i_bounces@5KPL>
```

postsrsd-1.5 on FreeBSD 11.3

In every case the mail is a Delivery Status Notification (Failure).

**Comment by roehling** [comment]
Does this issue still occur with the latest release?

**Comment by roehling** [comment]
I just realized that the incoming SRS1 addresses are invalid. The scheme requires that SRS1 addresses [must adhere](https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme#The_rewriting_scheme) to the following format: `SRS1=${HASH}=${ORIGINAL_DOMAIN}==${IMPLEMENTATION_DEFINED_STRING}@example.com`.

**Comment by philkernick** [comment]
But every one of those SRS1 addresses was created by postsrsd.

**Comment by roehling** [comment]
Can you show me the log entries for the srs_forward procedure? Because the above snippets are (part of) the srs_reverse transformation only.
