### ISSUE TITLE
SRS_DOMAIN / wrong default value

### ISSUE THREAD

**Issue by billynoah** [roehling/postsrsd#102]
The comments in `/etc/default/postsrsd` read:
```
# Local domain name.
# Addresses are rewritten to originate from this domain. The default value
# is taken from `postconf -h mydomain` and probably okay.
```
But without an explicit value set it seems to use `localhost@localdomain`.  I've checked `postconf -h mydomain` and it returns the correct value but is not used.  Instead I end up with a process like this:

    /usr/sbin/postsrsd -f 10001 -r 10002 -d localhost.localdomain -s /etc/postsrsd.secret -a = -u postsrsd -c /usr/local/lib/postsrsd -X

This is a default installation on Ubuntu 18.04.

**Comment by roehling** [comment]
Apparently, there is an issue with the [systemd service file](https://github.com/roehling/postsrsd/blob/master/init/postsrsd.systemd.in). I'm not sure why the PreExec call fails though.

**Comment by roehling** [comment]
This should be fixed with the latest release, as I completely rewrote the systemd service file logic.
