### ISSUE TITLE
Loophole of rewriting destination address?

### ISSUE THREAD

**Issue by SamuelJBHK** [roehling/postsrsd#104]
I am not sure if it's a loophole or not.  I found a message had been bounced back.  I checked the log messages and found that PostSRSd rewrote the destination address.  The destination address was something like this: `srs0+xxxx=Xv=hotmail.com=samueljbxxxx@mailserverdomainxxx.com`  It was rewritten to `samueljbxxxx@hotmail.com`.  Is there any way to avoid it?  Thanks!

I has tried to repeat the issue.  Below are log messages of the test done by myself.  Email addresses and domain are masked.

`Apr  6 18:30:09 vpshost postfix/smtpd[33501]: connect from mail-lf1-f43.google.com[209.85.167.43]
Apr  6 18:30:11 vpshost postfix/smtpd[33501]: Anonymous TLS connection established from mail-lf1-f43.google.com[209.85.167.43]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Apr  6 18:30:12 vpshost policyd-spf[33503]: None; identity=helo; client-ip=209.85.167.43; helo=mail-lf1-f43.google.com; envelope-from=samuelgmxxxx@gmail.com; receiver=srs0+xxxx=Xv=hotmail.com=samueljbxxxx@mailserverdomainxxx.com
Apr  6 18:30:12 vpshost policyd-spf[33503]: Pass; identity=mailfrom; client-ip=209.85.167.43; helo=mail-lf1-f43.google.com; envelope-from=samuelgmxxxx@gmail.com; receiver=srs0+xxxx=Xv=hotmail.com=samueljbxxxx@mailserverdomainxxx.com
Apr  6 18:30:12 vpshost postsrsd[33502]: srs_reverse: <srs0+xxxx=Xv=hotmail.com=samueljbxxxx@mailserverdomainxxx.com> rewritten as <samueljbxxxx@hotmail.com>
Apr  6 18:30:12 vpshost postfix/smtpd[33501]: 709BC80D25: client=mail-lf1-f43.google.com[209.85.167.43]
Apr  6 18:30:12 vpshost postsrsd[33505]: srs_forward: <samuelgmxxxx@gmail.com> rewritten as <SRS0+o5ey=5W=gmail.com=samuelgmxxxx@mailserverdomainxxx.com>
Apr  6 18:30:12 vpshost postsrsd[33506]: **srs_reverse: <srs0+xxxx=Xv=hotmail.com=samueljbxxxx@mailserverdomainxxx.com> rewritten as <samueljbxxxx@hotmail.com>**
Apr  6 18:30:13 vpshost postfix/cleanup[33504]: 709BC80D25: message-id=<CAGd=K17Zg1qQ9Wvv7X-Q1OHje8095h1hpZjC_dwtGkH3QHTuaQ@mail.gmail.com>
Apr  6 18:30:13 vpshost postfix/cleanup[33504]: 709BC80D25: warning: header Subject: Re: SRS Test from mail-lf1-f43.google.com[209.85.167.43]; from=<srs0+o5ey=5w=gmail.com=samuelgmxxxx@mailserverdomainxxx.com> to=<samueljbxxxx@hotmail.com> proto=ESMTP helo=<mail-lf1-f43.google.com>
Apr  6 18:30:13 vpshost postfix/qmgr[1427]: 709BC80D25: from=<srs0+o5ey=5w=gmail.com=samuelgmxxxx@mailserverdomainxxx.com>, size=4401, nrcpt=1 (queue active)
Apr  6 18:30:13 vpshost postfix/smtpd[33501]: disconnect from mail-lf1-f43.google.com[209.85.167.43] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Apr  6 18:30:13 vpshost postfix/smtp[33507]: 709BC80D25: to=<samueljbxxxx@hotmail.com>, orig_to=<SRS0+JJkx=5W=hotmail.com=samueljbxxxx@mailserverdomainxxx.com>, relay=hotmail-com.olc.protection.outlook.com[104.47.6.33]:25, delay=2.1, delays=1.3/0.01/0.64/0.2, dsn=5.7.1, status=bounced (host hotmail-com.olc.protection.outlook.com[104.47.6.33] said: 550 5.7.1 Unfortunately, messages from [xxx.xxx.xxx.xxx] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [VE1EUR02FT047.eop-EUR02.prod.protection.outlook.com] (in reply to MAIL FROM command))
Apr  6 18:30:13 vpshost postfix/smtp[33507]: 709BC80D25: lost connection with hotmail-com.olc.protection.outlook.com[104.47.6.33] while sending RCPT TO
Apr  6 18:30:13 vpshost postsrsd[33505]: srs_forward: <""> not rewritten: No at sign in sender address
Apr  6 18:30:13 vpshost postsrsd[33506]: srs_reverse: <srs0+o5ey=5w=gmail.com=samuelgmxxxx@mailserverdomainxxx.com> rewritten as <samuelgmxxxx@gmail.com>
Apr  6 18:30:13 vpshost postsrsd[33506]: srs_reverse: <srs0+o5ey=5w=gmail.com=samuelgmxxxx@mailserverdomainxxx.com> rewritten as <samuelgmxxxx@gmail.com>
Apr  6 18:30:13 vpshost postfix/cleanup[33504]: E371981095: message-id=<20200406103013.E371981095@vpshost.nuage.hk>
Apr  6 18:30:13 vpshost postfix/bounce[33508]: 709BC80D25: sender non-delivery notification: E371981095
Apr  6 18:30:13 vpshost postfix/qmgr[1427]: E371981095: from=<>, size=7289, nrcpt=1 (queue active)
Apr  6 18:30:13 vpshost postfix/qmgr[1427]: 709BC80D25: removed
Apr  6 18:30:15 vpshost postfix/smtp[33507]: E371981095: to=<samuelgmxxxx@gmail.com>, orig_to=<srs0+o5ey=5w=gmail.com=samuelgmxxxx@mailserverdomainxxx.com>, relay=gmail-smtp-in.l.google.com[108.177.97.27]:25, delay=1.9, delays=0.01/0/1.1/0.75, dsn=2.0.0, status=sent (250 2.0.0 OK  1586169015 x10si11966007plv.413 - gsmtp)
Apr  6 18:30:15 vpshost postfix/qmgr[1427]: E371981095: removed
`

**Comment by roehling** [comment]
The rewriting of the address is intentional. Consider the following situation

    [Server A] -----> [Server B] ----> [Server C]
    Sender            Forwarder        Accepts mail but then something goes wrong
                                           |
                    ???          <---------+  Bounce Notification

Now  `Server B` has to notify `Server A` of this bounce, or the original sender would mistakenly believe their message had been delivered. This is what the reverse rewrite is for. Think of it as a wrapper around the original email address, that gets unwrapped again if the message is returned to sender as undeliverable.

Technically, you could prevent this by removing the `recipient_canonical_maps` entry, which would render all bounces locally undeliverable. But you *really* should not do this, as it will hide any error that happens after you forwarded the email. (Say, you have a typo in your forwarding address. Nobody will notice. Say, the mailbox you forwarded to is full. Nobody will see the bounce.)

Let me repeat that: **don't do this**. You will be breaking fundamental assumptions about how email delivery is supposed to work.

Of course, as you have discovered, anyone who knows a valid rewritten address can misuse this address and relay emails through `Server B` back to `Server A`. For that reason, each rewritten address has a digital signature and a timestamp embedded. The timestamp makes sure that rewritten addresses become invalid after a few days (I believe 21 days by default), and the signature prevents bad actors from brute-forcing valid addresses.

**Comment by SamuelJBHK** [comment]
Thanks for your detail explanation!

I really think that someone knows how to produce a valid rewritten address of my server. Is it possible to stop him? Say, does it work by changing the secret key in `/etc/postsrsd.secret`?  Thanks for your help!

**Comment by roehling** [comment]
Yes, if you suspect that someone has compromised your key, you can run something like

    dd if=/dev/random bs=18 count=1 | base64 > /etc/postsrsd.secret
    systemctl restart postsrsd

This will create a new, random key and invalidate all old rewritten addresses instantly.

**Comment by SamuelJBHK** [comment]
I did it! Thanks!

One more side question: Is it ok to use longer secret key, say, bs=32?

**Comment by roehling** [comment]
You can use a longer key, but I don't think its necessary. Consider the two primary attack vectors:

The attacker can always try to guess valid addresses. The signature is truncated to 4 bytes by default, which translates to 24 bits of entropy. This means, an attacker has to try on average ~8 million combinations to find a valid hash for one(!) address. That's very noticeable in your logs and far too expensive for any spammer.

In contrast, guessing the secret would allow an attacker to forge as much addresses as he likes. The difficulty is pretty much the same as guessing the password for a WPA2-protected WiFi (it's the same HMAC hash algorithm). According to [this paper](https://eprint.iacr.org/2016/547.pdf), if you buy specialized hardware for $2000 and provide 25kW power, you can brute-force a secret with 34 bits in 24 hours. Extrapolating from this, it will take 2 days for 35 bits, 4 days for 36 bits, about a year for 43 bits, you get the idea. So 18 bytes, or 144 bits, seem pretty safe to me.
