### ISSUE TITLE
Is default hash length 4 safe enough?

### ISSUE THREAD

**Issue by powerman** [roehling/postsrsd#107]
Isn't such a short hash will make it easy enough to bruteforce and turn system into open relay? Why default is so small and is it really safe?

**Comment by roehling** [comment]
Brute-forcing the hash will yield a single valid address (as the hash is bound to the address), but requires roughly a million attempts, and you need to actually try and deliver a mail to see if your hash is correct.

So you need to try a million deliveries for a single mail to come through, which is hardly a tempting target for any spam mail sender, not to mention quite obvious in the server logs and easily defeated by temporary blocking senders with suspiciously high failure rates.

For an efficient open relay, you'd need to brute-force the signing secret of the HMAC algorithm, which is *much* harder. PostSRSd generates at least 128 secret bits by default at install time, and it takes many trillions of known-good hashes to break the algorithm.
