### ISSUE TITLE
unknown canonical_classes value "header_recipien" in "envelope_recipient, header_recipien"

### ISSUE THREAD

**Issue by abhikbose** [roehling/postsrsd#109]
I'm getting the following error message after installing postsrds:

`fatal: unknown canonical_classes value "header_recipien" in "envelope_recipient, header_recipien"`

This error is appearing each time I'm trying to send an email. And the mail is not sending. I'm using Postfix version 3.3.0 with Ubuntu 18.04. I've another system with the exact same setup working perfectly.

As a temporary fix, I've removed `header_recipien` from `canonical_classes` in `main.cf` and it's working now.

Can anyone please say me why is this happening and is it safe to remove `header_recipien` from `canonical_classes` in `main.cf`?

The `postsrds` configuration in `main.cf` after modification is as follows:

    sender_canonical_maps = tcp:localhost:10001
    sender_canonical_classes = envelope_sender
    recipient_canonical_maps = tcp:localhost:10002
    recipient_canonical_classes = envelope_recipient

The relevant section in `mail.log` is as follows

    Sep 12 05:30:57 mx02 postsrsd[30369]: srs_forward: <admin@example.com> rewritten as <SRS0=F0ZL=CV=example.com=admin@mx02.example.net>
    Sep 12 05:30:57 mx02 postfix/cleanup[30375]: fatal: unknown canonical_classes value "header_recipien" in "envelope_recipient,header_recipien"
    Sep 12 05:30:58 mx02 postfix/master[30320]: warning: process /usr/lib/postfix/sbin/cleanup pid 30375 exit status 1
    Sep 12 05:30:58 mx02 postfix/master[30320]: warning: /usr/lib/postfix/sbin/cleanup: bad command startup -- throttling
    Sep 12 05:31:57 mx02 roundcube: <ljjrbo70> PHP Error: Invalid response code received from server (POST /mail/?_task=mail&_unlock=loading1599888656818&_framed=1&_lang=en&_action=send)

Thanks in anticipation

**Comment by raoulbhatia** [comment]
Hi @abhikbose,

to me, it just looks like a typo /missing "t" in `header_recipient`.

Note: I am not using this software so I cannot validate myself.

**Comment by abhikbose** [comment]
Many thanks for your reply. It was indeed a missing `t`. Sorry for raising a silly issue. Closing the case.
