### ISSUE TITLE
Out of office not rewritten?

### ISSUE THREAD

**Issue by ovizii** [roehling/postsrsd#11]
Hi there,

I just got this out of office reply from a user hosted on my server using postsrsd. Any idea why the recipient (myself = ovidiu@pacura.ru) hasn't been nicely rewritten?

from:    sender@sa-tax.co.za
to:  SRS0+luma=2U=pacura.ru=ovidiu@h2118175.stratoserver.net
date:    22 May 2014 21:26
subject:     Out of office reply

Here is the corresponding log part:

May 22 21:26:15 h2118175 postfix/smtpd[334184]: connect from mail-ie0-f182.google.com[209.85.223.182]
May 22 21:26:16 h2118175 postfix/policyd-weight[574237]: decided action=PREPEND X-policyd-weight: using cached result; rate: -7; <client=mail-ie0-f182.google.com[209.85.223.182]> <helo=mail-ie0-f182.google.com> <from=ovidiu@pacura.ru> <to=sender@sa-tax.co.za>; delay: 0s
May 22 21:26:16 h2118175 postgrey[3279]: action=pass, reason=client whitelist, client_name=mail-ie0-f182.google.com, client_address=209.85.223.182, sender=ovidiu@pacura.ru, recipient=sender@sa-tax.co.za
May 22 21:26:16 h2118175 postfix/smtpd[334184]: AE960424081: client=mail-ie0-f182.google.com[209.85.223.182]
May 22 21:26:16 h2118175 postfix/cleanup[334930]: AE960424081: message-id=CAFtRoJGkr78Q7x6wGcWTcV_gPxLhT7yFCjMoo9ivQ-RO_FWsmw@mail.gmail.com
May 22 21:26:17 h2118175 postfix/qmgr[254084]: AE960424081: from=ovidiu@pacura.ru, size=11517, nrcpt=1 (queue active)
May 22 21:26:17 h2118175 postfix/smtpd[334184]: disconnect from mail-ie0-f182.google.com[209.85.223.182]
May 22 21:26:17 h2118175 postfix/smtpd[334934]: connect from localhost[127.0.0.1]
May 22 21:26:17 h2118175 postfix/smtpd[334934]: EBF294240C0: client=localhost[127.0.0.1]
May 22 21:26:17 h2118175 postsrsd[334935]: srs_forward: ovidiu@pacura.ru rewritten as <SRS0+luma=2U=pacura.ru=ovidiu@h2118175.stratoserver.net>
May 22 21:26:17 h2118175 postfix/cleanup[334930]: EBF294240C0: message-id=CAFtRoJGkr78Q7x6wGcWTcV_gPxLhT7yFCjMoo9ivQ-RO_FWsmw@mail.gmail.com
May 22 21:26:18 h2118175 postfix/qmgr[254084]: EBF294240C0: from=<SRS0+luma=2U=pacura.ru=ovidiu@h2118175.stratoserver.net>, size=12008, nrcpt=1 (queue active)
May 22 21:26:18 h2118175 postfix/smtpd[334934]: disconnect from localhost[127.0.0.1]
May 22 21:26:18 h2118175 amavis[319857]: (319857-02) Passed CLEAN {RelayedInbound}, [209.85.223.182]:49733 [209.85.223.182] ovidiu@pacura.ru -> sender@sa-tax.co.za, Queue-ID: AE960424081, Message-ID: CAFtRoJGkr78Q7x6wGcWTcV_gPxLhT7yFCjMoo9ivQ-RO_FWsmw@mail.gmail.com, mail_id: RVdw2Sh8DunE, Hits: -1.989, size: 11517, queued_as: EBF294240C0, 847 ms
May 22 21:26:18 h2118175 postfix/smtp[334931]: AE960424081: to=sender@sa-tax.co.za, relay=127.0.0.1[127.0.0.1]:10024, delay=1.7, delays=0.84/0.01/0/0.85, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as EBF294240C0)
May 22 21:26:18 h2118175 postfix/qmgr[254084]: AE960424081: removed
May 22 21:26:18 h2118175 dovecot: lda(sender@sa-tax.co.za): sieve: msgid=CAFtRoJGkr78Q7x6wGcWTcV_gPxLhT7yFCjMoo9ivQ-RO_FWsmw@mail.gmail.com: stored mail into mailbox 'INBOX'
May 22 21:26:18 h2118175 postfix/pickup[314494]: 5C9984240CF: uid=5000 from=<>
May 22 21:26:18 h2118175 postfix/cleanup[334930]: 5C9984240CF: message-id=dovecot-sieve-1400786778-58064-0@h2118175.stratoserver.net
May 22 21:26:18 h2118175 dovecot: lda(sender@sa-tax.co.za): sieve: msgid=CAFtRoJGkr78Q7x6wGcWTcV_gPxLhT7yFCjMoo9ivQ-RO_FWsmw@mail.gmail.com: sent vacation response to <SRS0+luma=2U=pacura.ru=ovidiu@h2118175.stratoserver.net>
May 22 21:26:18 h2118175 postfix/pipe[334937]: EBF294240C0: to=sender@sa-tax.co.za, relay=dovecot, delay=0.41, delays=0.08/0/0/0.33, dsn=2.0.0, status=sent (delivered via dovecot service)
May 22 21:26:18 h2118175 postfix/qmgr[254084]: EBF294240C0: removed
May 22 21:26:18 h2118175 postfix/qmgr[254084]: 5C9984240CF: from=<>, size=1024, nrcpt=1 (queue active)
May 22 21:26:19 h2118175 postfix/smtpd[334934]: connect from localhost[127.0.0.1]
May 22 21:26:19 h2118175 postfix/smtpd[334934]: B941D424081: client=localhost[127.0.0.1]
May 22 21:26:19 h2118175 postsrsd[334935]: srs_forward: <""> not rewritten: No at sign in sender address
May 22 21:26:19 h2118175 postsrsd[334936]: srs_reverse: <SRS0+luma=2U=pacura.ru=ovidiu@h2118175.stratoserver.net> rewritten as ovidiu@pacura.ru
May 22 21:26:19 h2118175 postfix/cleanup[334930]: B941D424081: message-id=dovecot-sieve-1400786778-58064-0@h2118175.stratoserver.net
May 22 21:26:19 h2118175 postfix/qmgr[254084]: B941D424081: from=<>, size=1583, nrcpt=1 (queue active)
May 22 21:26:19 h2118175 postfix/smtpd[334934]: disconnect from localhost[127.0.0.1]
May 22 21:26:19 h2118175 amavis[247302]: (247302-20) Passed CLEAN {RelayedInbound}, <> -> <SRS0+luma=2U=pacura.ru=ovidiu@h2118175.stratoserver.net>, Message-ID: dovecot-sieve-1400786778-58064-0@h2118175.stratoserver.net, mail_id: IhDnxPZlzvHm, Hits: -1.9, size: 1024, queued_as: B941D424081, 1415 ms
May 22 21:26:19 h2118175 postfix/smtp[334931]: 5C9984240CF: to=<SRS0+luma=2U=pacura.ru=ovidiu@h2118175.stratoserver.net>, relay=127.0.0.1[127.0.0.1]:10024, delay=1.6, delays=0.2/0/0/1.4, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as B941D424081)
May 22 21:26:19 h2118175 postfix/qmgr[254084]: 5C9984240CF: removed
May 22 21:26:20 h2118175 postfix/smtp[334954]: B941D424081: to=ovidiu@pacura.ru, orig_to=<SRS0+luma=2U=pacura.ru=ovidiu@h2118175.stratoserver.net>, relay=aspmx.l.google.com[173.194.65.27]:25, delay=1.3, delays=0.62/0.01/0.12/0.54, dsn=2.0.0, status=sent (250 2.0.0 OK 1400786780 g48si2306705eeo.50 - gsmtp)
May 22 21:26:20 h2118175 postfix/qmgr[254084]: B941D424081: removed

Any other info I can supply?

**Comment by fisher006** [comment]
I have this same issue.
Where I can put postmap -q<SENDER> tcp:127.0.0.1:10002 ?
directly in sieve filter?

**Comment by roehling** [comment]
The `postmap` command is part of the Postfix package and it's a binary. You cannot call binaries on the server from sieve scripts. This hack was intended for someone who runs a perl/shell/whatever script for the out-of-office replies.

**Comment by fisher006** [comment]
Ok thanks because I have this same problem recipient hasn't been nicely rewritten

https://github.com/roehling/postsrsd/issues/53

**Comment by pletschacher** [comment]
adding the following to main.cf fixed the out-of-office-response-problem. Same for delivery reports. Simply add:

`local_header_rewrite_clients = static:all`

**Comment by fisher006** [comment]
Unfortunately for me does not help

**Comment by NIXKnight** [comment]
I just found this thread and thanks to @roehling, I have implemented the hack he mentioned.

Just in case, if someone is still looking for the hack mentioned by @roehling, I have implemented this using PostfixAdmin **vacation.pl** script wrapped in **vacation.sh**:

```
#!/bin/bash

SRSD_SENDER="${1}"
AUTO_REPLY_RECIPIENT="${2}"

ORIGIN_SENDER=$(/usr/sbin/postmap -q$SRSD_SENDER tcp:127.0.0.1:10002)

/var/spool/vacation/vacation.pl -f ${ORIGIN_SENDER} ${AUTO_REPLY_RECIPIENT}
```
In **master.cf** you need add vacation as follows:

```
vacation    unix  -       n       n       -       -       pipe
        flags=Rhu user=vacation argv=/var/spool/vacation/vacation.sh ${sender} ${recipient}
```

**Comment by fisher006** [comment]
New pigeonhole fix this issue ;)


Here's the definitive 0.4.21 release. There were no changes since the
release candidate.

Changelog v0.4.21:

* redirect action: Always set the X-Sieve-Redirected-From header to
  sieve_user_email if configured. Before, it would use the envelope
  recipient instead if available, which makes no sense if the primary
  e-mail address is available.
+ vacation extension: Allow ignoring the envelope sender while composing
  the "To:" header for the reply. Normally, the "To:" header is composed
  from the address found in the "Sender", "Resent-From" or "From"
  headers that is equal to the envelope sender. If none is then found,
  the bare envelope sender is used. This change adds a new setting
  "sieve_vacation_to_header_ignore_envelope". With this setting enabled,
  the "To:" header is always composed from those headers in the source
  message. The new setting thus allows ignoring the envelope, which is
  useful e.g. when SRS is used.
+ vacation extension: Compose the "To:" header from the full sender
  address found in the first "Sender:", "From:" or "Resent-From:"
