### ISSUE TITLE
Systemd unit fails to start if postfix is not installed

### ISSUE THREAD

**Issue by oxan** [roehling/postsrsd#110]
In Debian I received a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975633) about postsrsd failing to start if Postfix isn't installed. This happens because the systemd service invokes `postconf` to determine the default domain, which fails.

https://github.com/roehling/postsrsd/blob/02efc02cce99eed318480a9d81217db475a82892/init/postsrsd.systemd.in#L14-L15

It's easy to make systemd ignore failure of such a `ExecStartPre` directive (prefix the value with a dash), but the current code will still write an empty value for `SRS_DOMAIN` in the default file in that case. 

I suggest replacing the `ExecStartPre` with the following, which checks if postconf exists before writing the default file, and makes systemd ignore the failure if postconf doesn't exist.
```
ExecStartPre=-/bin/sh -c 'command -v postconf >/dev/null && echo -n SRS_DOMAIN=$(postconf -h mydomain) >/run/postsrsd/default'
```

**Comment by roehling** [comment]
Thank you for the bug report, and I agree with your suggested solution. Personally, I can't think of a good reason to run PostSRSd without Postfix or on a separate machine, but there is no reason to have it as a hard dependency either.

Come to think of it, I can probably retire the Upstart code, too, while I am at it.

**Comment by oxan** [comment]
> Personally, I can't think of a good reason to run PostSRSd without Postfix

The reporter uses postsrsd with Exim, which is an unusual but reasonable usecase I think.

> Come to think of it, I can probably retire the Upstart code, too, while I am at it.

Yeah, I don't expect anybody still uses that.

**Comment by roehling** [comment]
I'm going to prepare a new release 1.7. I've seen your Debian specific patches, and I think I will include everything except the dedicated postsrsd user, mostly because adding a user seems quite intrusive for a distribution-agnostic installer.

**Comment by oxan** [comment]
Thanks!

That's fine, I'll keep carrying the dedicated user in Debian, no problem. I think most of the rest of the patches were to keep functioning when the default file is deleted, but I was going to drop that for the next version, since it's no longer a requirement in Debian (I don't think it was a particularly sensible requirement anyway).

**Comment by oxan** [comment]
I was mistaken, it's apparently still required in Debian to function properly when the `/etc/default` file is removed. So thanks for merging that patch! :)
