### ISSUE TITLE
Systemd service startup failure in PostSRSd 1.8 / `SRS_EXTRA_OPTIONS` empty argument

### ISSUE THREAD

**Issue by onlime** [roehling/postsrsd#112]
On Debian Buster 10.6, Systemd service unit `postsrsd.service` fails to start up **PostSRSd 1.8**. All was working fine with previous PostSRSd 1.7.

The reason can be found in `journalctl`:

```
$ journalctl -u postsrsd
Dec 04 12:51:07 mail systemd[1]: postsrsd.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Dec 04 12:51:08 mail systemd[1]: Stopping PostSRSd Daemon...
Dec 04 12:51:08 mail systemd[1]: postsrsd.service: Main process exited, code=killed, status=15/TERM
Dec 04 12:51:08 mail systemd[1]: postsrsd.service: Succeeded.
Dec 04 12:51:08 mail systemd[1]: Stopped PostSRSd Daemon.
Dec 04 12:51:08 mail systemd[1]: Starting PostSRSd Daemon...
Dec 04 12:51:08 mail systemd[1]: Started PostSRSd Daemon.
Dec 04 12:51:08 mail postsrsd[10019]: postsrsd: extra argument on command line:
Dec 04 12:51:08 mail systemd[1]: postsrsd.service: Main process exited, code=exited, status=1/FAILURE
```

See diff of `postsrsd.systemd.in` here:

https://github.com/roehling/postsrsd/compare/1.7...1.8#diff-37e8ed44c127f64645c5a642434c37194a825b6c75cb742928b5503cee61c69d

The `extra argument on command line` error occurs because of the new empty argument (by default, we have not set `$SRS_EXTRA_OPTIONS`):

https://github.com/roehling/postsrsd/blob/b7fe5520900224290279084950a49c2be0b01839/postsrsd.c#L398-L401

This is a similar issue like #59

One solution to fix this would be to move `SRS_EXTRA_OPTIONS` to the end of the `postsrsd` command and use some [shell parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) so that the variable would only be prefixed by a space if it was not empty ...

```diff
-ExecStart=/usr/local/sbin/postsrsd -f "${SRS_FORWARD_PORT}" -r "${SRS_REVERSE_PORT}" -d "${SRS_DOMAIN}" -s "${SRS_SECRET}" -a "${SRS_SEPARATOR}" -n "${SRS_HASHLENGTH}" -N "${SRS_HASHMIN}" -u "${RUN_AS}" -l "${SRS_LISTEN_ADDR}" -c "${CHROOT}" "-X${SRS_EXCLUDE_DOMAINS}"
+ExecStart=/usr/local/sbin/postsrsd -f "${SRS_FORWARD_PORT}" -r "${SRS_REVERSE_PORT}" -d "${SRS_DOMAIN}" -s "${SRS_SECRET}" -a "${SRS_SEPARATOR}" -n "${SRS_HASHLENGTH}" -N "${SRS_HASHMIN}" -u "${RUN_AS}" -l "${SRS_LISTEN_ADDR}" -c "${CHROOT}" "-X${SRS_EXCLUDE_DOMAINS}"${SRS_EXTRA_OPTIONS:+ }${SRS_EXTRA_OPTIONS}
```

But hey, this is not going to work, as Systemd is no Bash!

@roehling hope you find some smarter solution to fix this. I guess you can just somehow improve your arguments sanity check in `postsrsd.c`.
Thanks for this great project! PostSRSd runs very robust for years now.
Cheers,
Philip

**Comment by roehling** [comment]
Sigh, I love systemd argument expansion… I'll have a look and try to come up with a better solution.

**Comment by roehling** [comment]
I went with the simplest solution and added a wrapper script that `exec`s the main daemon. This way, I can rely on somewhat sane parameter expansion. There's no runtime overhead (as the shell executable image gets replaced by the daemon), and miniscule startup overhead.

**Comment by onlime** [comment]
nice @roehling ! Thanks for releasing 1.9 so fast. It's already running in production on one of our mail servers. Looks great, your `postsrsd-systemd-launcher` wrapper script workaround for Systemd!
