### ISSUE TITLE
SRS rewrites every single incoming email

### ISSUE THREAD

**Issue by Basili0** [roehling/postsrsd#14]
I'm running a postfix+dovecot+mysql with virtual domains, and ran into problems with using postsrsd rewriting absolutely every e-mail going through it, like this:
Jul  6 07:02:02 cs12986 postfix/smtpd[18361]: connect from smtp.zagruzka.com[194.85.19.154]
Jul  6 07:02:02 cs12986 postfix/smtpd[18361]: Anonymous TLS connection established from smtp.zagruzka.com[194.85.19.154]: TLSv1 with cipher AES256-SHA (256/256 bits)
Jul  6 07:02:02 cs12986 postgrey[24863]: action=pass, reason=triplet found, client_name=smtp.zagruzka.com, client_address=194.85.19.154, sender=noc@zagruzka.com, recipient=mgudkova@euct.ru
Jul  6 07:02:02 cs12986 postfix/smtpd[18361]: C9ED17BE538: client=smtp.zagruzka.com[194.85.19.154]
Jul  6 07:02:02 cs12986 postsrsd[18573]: srs_forward: noc@zagruzka.com rewritten as <SRS0+S7Ai=4B=zagruzka.com=noc@euct.ru>
Jul  6 07:02:02 cs12986 postfix/cleanup[18572]: C9ED17BE538: message-id=<53b8bc2a.cvFkybUdtXpFIqQg%noc@zagruzka.com>
Here we have an external e-mail coming to a local virtual mailbox. Why is it rewriting the sender's address?
Is this intended behavior, and all local domains should be added to SRS_EXCLUDE_DOMAINS?

**Comment by nyetwurk** [comment]
Why is this closed? I have the same issue with local mail, and local virtual mailboxes
