### ISSUE TITLE
/usr/sbin/postsrsd: unrecognized option: f

### ISSUE THREAD

**Issue by genotix** [roehling/postsrsd#148]
When running the Docker image (from a Synology NAS) the latest version won't start and shows me the error
`/usr/sbin/postsrsd: unrecognized option: f`

No changes have been made on the config for a long time.

**Comment by roehling** [comment]
This sounds like the Docker image updated to PostSRSd 2.0 without properly migrating the configuration settings.

**Comment by roehling** [comment]
I am not building nor supporting any Docker images, so you should probably talk to whoever created the image in the first place.

**Comment by genotix** [comment]
My bad; I thought it was you.
Can’t imagine the person is running this himself since there’s clearly a basic issue.

Thanks for your developments so far.

> I am not building nor supporting any Docker images, so you should probably talk to whoever created the image in the first place.
