### ISSUE TITLE
invalid socketmap query, closing connection

### ISSUE THREAD

**Issue by dominicraf** [roehling/postsrsd#150]
Thanks for the new 'debug = ' setting, but after updating to this (using `git clone`, previously I had downloaded 2.0.5 as zip file) I now find that although postsrsd seems to be working, after every(?) call I get a log entry of this type, which didn't happen before:

`2023-07-15 09:01:14 server1 postsrsd[1961170]: invalid socketmap query, closing connection`

(This is irrespective of the debug setting)

**Comment by roehling** [comment]
Oh, looks like I have been overzealous in my attempt to log all error conditions :)
Fix is incoming.

**Comment by roehling** [comment]
Can you verify that the latest `HEAD` fixes the problem and then close this issue? (Or tell me no if it does not, of course)

**Comment by dominicraf** [comment]
yes that's it, thanks.
