### ISSUE TITLE
Connection refused after upgrade to 2.0

### ISSUE THREAD

**Issue by gldecurtins** [roehling/postsrsd#164]
Dear all

I've been using postsrsd for some years now, but somehow I can't get version 2.0 running with my setup.

The FreeBSD server has some aliases in /etc/aliases:
`other_user_at_gmail.com:   "|/usr/local/bin/postforward.py other.user@gmail.com"
`

My [Python script](https://github.com/gldecurtins/postforward/blob/main/postforward.py) was used to connect to the postsrsd daemon via port 10001. But now it fails with
`Traceback (most recent call last):
  File "/usr/local/bin/postforward.py", line 92, in <module>
    main()
  File "/usr/local/bin/postforward.py", line 73, in main
    SRSReturnPath = _getSRSReturnPath(returnPath, SRSHOST, SRSPORT)
  File "/usr/local/bin/postforward.py", line 40, in _getSRSReturnPath
    sock.connect((SRSHOST, SRSPORT))
ConnectionRefusedError: [Errno 61] Connection refused`

Is this kind of setup no longer supported? Or am I missing something?

Cheers

**Comment by roehling** [comment]
Quoting the [README.rst](https://github.com/roehling/postsrsd#migrating-from-version-1x):
> Be aware that PostSRSd 2.x uses socketmap: tables, which are NOT compatible with tcp: tables.

Your setup can still work, but you need to communicate with a [different protocol](https://www.postfix.org/socketmap_table.5.html). This is also why I deliberately changed the default port. As you are using Python, you may find the `read_netstring` and `write_netstring` functions in [tests/blackbox/socketmap.py](https://github.com/roehling/postsrsd/blob/main/tests/blackbox/socketmap.py) helpful.

**Comment by gldecurtins** [comment]
Thanks a lot! I thought this change just impacted the communication between Postfix and postsrsd. I'll fix my script accordingly.
