### ISSUE TITLE
domains-file not working

### ISSUE THREAD

**Issue by tk7936** [roehling/postsrsd#177]
Hello, 
in docs it is written:

# Example:
#     domains-file = "/usr/local/etc/postsrsd.domains"

for local domains so they do not get rewritten but my domain-file is being ignored.
I can not find a description of its format either.
How does the domain-file have to look to work properly ?
Currently i have
domain1
domain2
domain3 
ect.

Thankyou very any help!

**Comment by roehling** [comment]
The file format is one domain per line (documentation added in ac7c853aa7a5e991eedc8c3486360c3918b70e64). The example is only a comment in the file, so if you want to actually use the `domains-file` setting, you need to un-comment it (or create a separate line with `domains-file = ...` in the config file).

**Comment by tk7936** [comment]
Thanks for updating the doc. Unfortunatly it still doesnt work. 
In  /etc/default/postsrsd
i have:
domains-file = "/etc/postsrsd.domains"

The Domains are 1 each line. But all of them get rewritten anyway.
