### ISSUE TITLE
Make domains_file ignore comments?

### ISSUE THREAD

**Issue by gilgongo** [roehling/postsrsd#181]
I would expect some Postfix admins (like me) might be using a file to list local domains with `$mydestination` in `main.cf`. 

However, if I point postsrsd (2.0.9) to that file, I see it doesn't allow comments in the same way that Postfix does:

`postsrsd: error: invalid domain name '# This is a comment' in domains file`

Would be nice if it could ignore those so that both Postfix and postsrsd could use the same file :-)

**Comment by roehling** [comment]
Agreed! I put it on my to-do list and hopefully, I won't take long...
