### ISSUE TITLE
Problem with starting postfix after installation postsrsd

### ISSUE THREAD

**Issue by Keiishi** [roehling/postsrsd#25]
Hello,

I have an little problem with starting my postfix v2.6 after implementing postsrsd.

Im working on centos 6.5, ad got error as below.

postfix/cleanup[2629]: fatal: unsupported dictionary type: tcp
postfix/master[2376]: warning: process /usr/libexec/postfix/cleanup pid 2629 exit status 1
postfix/master[2376]: warning: /usr/libexec/postfix/cleanup: bad command startup -- throttling

Im almost sure that it is becouse of "sender_canonical_maps = tcp:127.0.0.1:10001 and "recipient_canonical_maps = tcp:127.0.0.1:10002" in main.cf, because in whole configuration there's only there text tcp

I tried to find how to deal with that, but unfortunatelly didnt find any topic with that kind of problem ..

Any idea how to deal with that?

Thanks in advance for any tips how to deal with that.

Best regards
Keiishi

**Comment by adamjimenez** [comment]
I had the same problem and appears to have resulted in mail being dropped (not good). Is it possible to do a postfix version check in advance to prevent others from having the same headaches?

**Comment by roehling** [comment]
Well, it is explicitly stated in the "Known Issues" section of the README.
