### ISSUE TITLE
postsrsd: Poll failure: Interrupted system call

### ISSUE THREAD

**Issue by garblix** [roehling/postsrsd#30]
Hello Timo,

I installed postsrsd (1.1-1~raring) from your repository at https://launchpad.net/~roehling/+archive/ubuntu/stable on a Debian stable.
postsrsd runs fine but sometimes it crashes with the following syslog entry:

###############
postsrsd[3992]: Poll failure: Interrupted system call
###############

Is this a known bug, or should I inspect my system for errors?

Thanks for your effort!
Klaus

**Comment by roehling** [comment]
Yes, this is a known problem (I was overzealous as EINTR can occur for benign reasons), and it is fixed since 6abd042ee3abbbc718ca4e4955869138744bedad. I did not build a new debian package though, mostly because there are a few other issues I wanted to fix but did not get around to yet.

**Comment by garblix** [comment]
Hello Timo,

thanks for your quick reply and the explanation.
I was able to build a debian package myselfs from the latest git.

Thanks for your package an the fine work!

Bye Klaus

Timo Röhling schrieb am 03.02.2015 um 09:24:
