### ISSUE TITLE
CentOS 6 service won't start with "postsrsd: You must set a secret (-s)"

### ISSUE THREAD

**Issue by robertlandes** [roehling/postsrsd#33]
I downloaded latest master, compiled and installed. Everything seems fine until I try to start the service. I always get the following error: `Starting Postfix Sender Rewriting Scheme daemon: postsrsd: You must set a secret (-s) [FAILED]`. I checked init scipts, config files and also `/etc/postsrsd.secret` everything looks fine and I can start manually on the command line.

**Comment by roehling** [comment]
This one was complicated to hunt down. It turns out that the way I wrote the startup scripts, empty values for configuration variables cause it to gobble up the next command line option. Most likely, the SRS_DOMAIN variable is not set correctly.

**Comment by robertlandes** [comment]
Okay, I will give it a try and report back.
