### ISSUE TITLE
It's possible to use postsrsd only for outgoing emails?

### ISSUE THREAD

**Issue by ewake** [roehling/postsrsd#34]
Hi,
i would like to use postsrsd only for outgoing emails, how can i do that?
I tried to comment these lines on Postfix:

    sender_canonical_maps = tcp:127.0.0.1:10001
    sender_canonical_classes = envelope_sender
    #recipient_canonical_maps = tcp:127.0.0.1:10002
    #recipient_canonical_classes = envelope_recipient

Any help is appreciated, thank you.

**Comment by roehling** [comment]
Unfortunately, that's not possible at the moment (see the Known Issue at the end of the README). If the envelope rewrite really bothers you, Postfix can be configured in a way that separates different tasks like local delivery and forwarding into separate Postfix instances. But it is not easy to set up correctly.

**Comment by ewake** [comment]
Thanks, i'll look at what you say if it is not too hard..
Anyway congratulations for postsrsd: is a very helpful solution!
