### ISSUE TITLE
First separator - plus or equals

### ISSUE THREAD

**Issue by nichivo** [roehling/postsrsd#35]
The RATWARE_EFROM SpamAssassin check was catching mail as it only excludes "SRS0=". SpamAssassin probably should exclude at least [+-=] but I was wondering if there was a reason postsrsd hardcodes the use of "+" in line 458 in postsrsd.c:

`srs_set_separator (srs, '+');`

I just removed the line which defaults to "=". I guess it would be nice to have a config option for it but is there a reason it's overridden in code or just personal preference at the time?

**Comment by roehling** [comment]
The override is actually for "historical" reasons: my first script used '+' because then I could treat SRS0 and SRS1 as accounts ('+' is the address extension separator). I agree it would be nice to have a config option for that.

**Comment by nichivo** [comment]
...and now there is a config option ;)

See #36

**Comment by roehling** [comment]
Thanks for the pull request!
