### ISSUE TITLE
Long strings don't give correct answer

### ISSUE THREAD

**Issue by venomcom2krew** [roehling/postsrsd#37]
* As you can see in the logs, long strings give: unexpected EOF (Connection timed out)

Jun 19 18:26:06 ifmx03 postfix/cleanup[12280]: warning: read TCP map reply from 127.0.0.1:10002: unexpected EOF (Connection timed out)
Jun 19 18:26:06 ifmx03 postfix/cleanup[12280]: warning: tcp:127.0.0.1:10002 lookup of "Marian mare de Violeta Brizuela 3r  EP <marianbri@xxxxxxx.com>;  Merche mare Nico  <costyalbanil@xxxxx.co>;   Cristina i
Muriel mares de Mar  <murielmiravet@xxxxx.com>;  Eduard pare  Marc Guerau  <eduard.comeig@xxxxx.com>;  Empar mare Emma i Marcel   <emparlorente@xxxxx.com>;  Enric Camps pare Aitana   <enriccampsvalero@xxxxx.c
om>;  estherolga  <estheresteveroc@xxxxxxx.com>;   Helena Mare Mar?a  <marole12@xxxxx.com>;  Hugo Talens  <neli@xxxxxxx.net>;   Iker ContrerasMamen  <carod.mar@xxxxxxx.com>;  Isabel mare Iker Garc?a   <info@i
sabelpallardo.com>;  Isabel Mart?nez   <isabel.martinez@puntmobles.com>;  Joan fill de M? Jos? germana Isabel  pallard?  <pa.majo@xxxxxxx.com>;  Jose Antonio Moreno   <josantmoreno@xxxxx.com>;  Lucas Casaban
 <stmasiaperdida@xxxxx.com>;   Luc?a Navarro  <chechuleile@xxxxx.com>;  Mar mare de Luc?a i Alex Baixauli   <abebri@xxxxxxx.com>;  SONIA marco  <silvecent@xxxxx.com>;  maria jose  marc costa  <maria.jose.cost
a@xxxx.xx.xx>;  Marian mare de Violeta Brizuela  3r EP  <marianbri@xxxxxxx.com>;  Merche mare Nico"@xxxx.xx.xx failed
Jun 19 18:26:06 ifmx03 postfix/cleanup[12280]: warning: CAA3EA03C5: recipient_canonical_maps map lookup problem for "Marian mare de Violeta Brizuela 3r  EP <marianbri@xxxxxxx.com>;  Merche mare Nico  <costyal
banil@xxxxx.co>;   Cristina i Muriel mares de Mar  <murielmiravet@xxxxx.com>;  Eduard pare  Marc Guerau  <eduard.comeig@xxxxx.com>;  Empar mare Emma i Marcel   <emparlorente@xxxxx.com>;  Enric Camps pare Aita
na   <enriccampsvalero@xxxxx.com>;  estherolga  <estheresteveroc@xxxxxxx.com>;   Helena Mare Mar?a  <marole12@xxxxx.com>;  Hugo Talens  <neli@xxxxxxx.net>;   Iker ContrerasMamen  <carod.mar@xxxxxxx.com>;  Isa
bel mare Iker Garc?a   <info@xxxxxxxxxxxxxx.com>;  Isabel Mart?nez   <isabel.martinez@xxxxxxxxxx.com>;  Joan fill de M? Jos? germana Isabel  pallard?  <pa.majo@xxxxxxx.com>;  Jose Antonio Moreno   <josantmore
no@xxxxx.com>;  Lucas Casaban  <stmasiaperdida@xxxxx.com>;   Luc?a Navarro  <chechuleile@xxxxx.com>;  Mar mare de Luc?a i Alex Baixauli   <abebri@xxxxxxx.com>;  SONIA marco  <silvecent@xxxxx.com>;  maria jose
  marc costa  <maria.jose.costa@xxxx.xx.xx>;  Marian mare de Violeta Brizuela  3r EP  <marianbri@xxxxxxx.com>;  Merche mare Nico"@xxxx.xx.xx
Jun 19 18:26:06 ifmx03 postsrsd[12854]: srs_forward: <double-bounce@ifmx03.local> rewritten as <SRS0+N+PT=G5=ifmx03.local=double-bounce@xxxx.xx.xx>

* Postfix version:
Name        : postfix                      
Version     : 2.8.12                            
Release     : 1.vda.el6

**Comment by roehling** [comment]
How did you configure PostSRSd? It should look up addresses individually, not as a complete list.

**Comment by venomcom2krew** [comment]
Hi,
I think I configured it in the recommended way. The relevant part of the /etc/postfix/main.cf:

# SRS forwarding address rewriting
# https://github.com/roehling/postsrsd
sender_canonical_maps = tcp:127.0.0.1:10001
sender_canonical_classes = envelope_sender
recipient_canonical_maps = tcp:127.0.0.1:10002
recipient_canonical_classes= envelope_recipient,header_recipient


Date: Mon, 22 Jun 2015 07:15:49 -0700

**Comment by roehling** [comment]
Whatever you did, Postfix treats your whole list of recipients as one giant email address and passes it to PostSRSd verbatim. Obviously, the program you are using to send the email does not separate the list into its constituent addresses properly and dumps it into Postfix as a single address instead.

I can't tell you how to fix that, but I notice that the list uses semicolon (;) instead of comma (,) as list separator. Maybe that's the problem?

**Comment by roehling** [comment]
Closing this issue now...
