### ISSUE TITLE
SRS_EXCLUDE_DOMAINS cannot be separated by spaces

### ISSUE THREAD

**Issue by msteen** [roehling/postsrsd#38]
If the setting SRS_EXCLUDE_DOMAINS is defined with multiple domains separated by spaces OpenSRSD will fail to start. Separating them by commas does work, it then works as expected.

**Comment by roehling** [comment]
Which system are you using? In particular, which init daemon (systemd, upstart,...)?

**Comment by msteen** [comment]
I am running Ubuntu 12.04 LTS, so I am using Upstart. The version of Postfix is 2.9.6.

**Comment by roehling** [comment]
This may be related to issue #44. Can you check if it works with the latest version?

**Comment by roehling** [comment]
I assume this has been fixed
