### ISSUE TITLE
postsrsd changing From: header in body

### ISSUE THREAD

**Issue by shashisingh** [roehling/postsrsd#39]
I am using postsrsd for SRS rewriting with Postfix. I can see MAIL FROM: address has been modified to SRS rewritten address. Along with that, I can see that even MIME From: header has been rewritten. Because of that when this email is received by the recipient, it is shown to come from SRS written address instead of being from original sender. Is there a way to prevent MIME From: header from being replaced with SRS address?

**Comment by bjoe2k4** [comment]
postfix `sender_canonical_classes` option is your friend. Actually if you stick to the postsrsd recommended settings (see README) then this should not happen.

**Comment by shashisingh** [comment]
I have set sender_canonical_classes to "envelope_sender" as described in the README. It is my understanding that this setting should imply that only envelope header (i.e. MAIL FROM:, RCTP TO: etc.) will be replaced and header_sender (From:, To: in MIME body) will not be replaced. But still I see this issue.

**Comment by bjoe2k4** [comment]
What do the logs say?

**Comment by bkuhn** [comment]
I have sender_canonical_classes properly configured.  I can produce this problem in the following way:
with the configuration as the README suggests, send an email with *no* From: header in it, and set your envelope information to a domain handled as a virtual_alias_domains (i.e., not the primary domain of the mail server).

I find that the SRS-formatted envelope sender in this case ends up in the From:

I suppose this can't be prevented, and really you should be submitting outgoing mail with a From: header in place, but I've been unable to find the setting in Postfix which decides what to add into the From, but whatever it is, it's using the SRS rewritten information when postsrsd is activated, and DTRT (uses USERNAME@VIRTUALDOMAIN.tld) when postsrsd is deactivated.

If this is a bug, I think it's primary needed action is to add an explanation of how to handle virtual_alias_domains and empty From: headers in the docs.

**Comment by roehling** [comment]
The missing header is added by the Postfix cleanup daemon (see the manual page), after it has consulted the canonical_* maps, that's why the rewritten address ends up in the From: header.

**Comment by romuloceccon** [comment]
The correct solution is to always set the "From:"-header, but sometimes it's not possible to control that, and using SRS-remapping just makes things worse. One such example are mails sent from Ubuntu's unattended upgrades system. A possible workaround is to use Postfix's [header checks](http://www.postfix.org/header_checks.5.html):

```
/etc/postfix/main.cf:
    smtp_header_checks = pcre:/etc/postfix/header_checks

/etc/postfix/header_checks:
    /^From:[[:space:]]*SRS0[[:print:]]*=([[:print:]]+?)=([[:print:]]+?)@[[:print:]]*?[[:space:]]*$/ REPLACE From: ${2}@${1}
```

**Comment by roehling** [comment]
Closing this issue, since it seems to be stale. Feel free to reopen.
