### ISSUE TITLE
Upstart script faulty?

### ISSUE THREAD

**Issue by tdelenikas** [roehling/postsrsd#44]
Hello and best wishes for the new year!

Although I've installed postsrsd (from master) in the past without problems, I faced a problem today, installing it on a fresh Ubuntu 14.04.3 again from master repo.

Postsrsd would not start.

I've searched around a bit and landed on #26. But it didn't help me at all.

I started to check the new scripts with the scripts of another installation, and I've found a difference in the upstart script:

```
exec /usr/sbin/postsrsd -f "$SRS_FORWARD_PORT" -r "$SRS_REVERSE_PORT" -d "$SRS_DOMAIN" -s "$SRS_SECRET" -a "$SRS_SEPARATOR" -u "$RUN_AS" -c "$CHROOT" -X "$SRS_EXCLUDE_DOMAINS"
```

I've noticed a space between each parameter that wasn't there in the old script. So I've removed the spaces to read:

```
exec /usr/sbin/postsrsd -f"$SRS_FORWARD_PORT" -r"$SRS_REVERSE_PORT" -d"$SRS_DOMAIN" -s"$SRS_SECRET" -a"$SRS_SEPARATOR" -u"$RUN_AS" -c"$CHROOT" -X"$SRS_EXCLUDE_DOMAINS"
```

and postsrsd started without problems! No other changes were made.

Regards,
Thanasis.

**Comment by sheldon** [comment]
I had this same problem, confirmed this fix works.

**Comment by Natolumin** [comment]
in [postsrsd.c:262](https://github.com/roehling/postsrsd/blob/master/postsrsd.c#L262), -X has an *optional* argument (whereas all the others are mandatory). The manual for getopt indicates : 
>if  there  is  text  in the current argv-element (i.e., in the same word as the option name itself, for
       example, "-oarg"), then it is returned in optarg, otherwise optarg is set to zero

In 855bd4 a space was added in all scripts (as you noted). I believe setting the exec line to (notice only the space after -X is removed): 

    exec /usr/sbin/postsrsd -f "$SRS_FORWARD_PORT" -r "$SRS_REVERSE_PORT" -d "$SRS_DOMAIN" -s "$SRS_SECRET" -a "$SRS_SEPARATOR" -u "$RUN_AS" -c "$CHROOT" -X"$SRS_EXCLUDE_DOMAINS"

would be enough to workaround this (it does for me) additionally, it would not reintroduce #33, since there is no other option afterwards to be eaten by an empty argument.

Another solution would be to simply make the argument for -X mandatory, I guess

**Comment by roehling** [comment]
Nice catch, thanks guys. I will change the command line accordingly in all scripts.

**Comment by aptalca** [comment]
Thanks so much, it was driving me nuts as I couldn't figure out why postsrsd was failing.

Deleting the space after the -X in the upstart script fixed it.

It works great

**Comment by jonhoo** [comment]
Note that this also affects the systemd startup script.

**Comment by raimue** [comment]
When started by systemd, this will now result in a literal `-X"${SRS_EXCLUDE_DOMAINS}"` on the command line. That is, the quotes are part of the argument that is passed to postsrsd. The first and last domain in the exclude list are therefore not being recognized correctly. I assume this should be  `"-X${SRS_EXCLUDE_DOMAINS}"`.

As an immediate workaround I added dummy entries at the front and back of the list in my configuration.
