### ISSUE TITLE
FreeBSD + clang: some fixes

### ISSUE THREAD

**Issue by wtps0n** [roehling/postsrsd#45]
Hello,

I'm a maintainer of mail/postsrsd at FreeBSD ports tree. I've just testing last release of postsrsd to make a port update. I had some compilation errors. So I think it could be added to source code.

--- srs2.c.orig 2015-12-13 08:56:05 UTC
+++ srs2.c
@@ -21,7 +21,11 @@
 #include <sys/types.h>  /* tyepdefs */
 #include <sys/time.h>   /* timeval / timezone struct */
 #include <string.h>            /* memcpy, strcpy, memset */
-#include <alloca.h>
+#if defined(__FreeBSD__)
+#  include <stdlib.h>
+#else
+#  include <alloca.h>
+#endif

 #ifdef USE_OPENSSL
 #include <openssl/hmac.h>

--- srs2.h.orig 2015-12-13 08:56:05 UTC
+++ srs2.h
@@ -23,7 +23,7 @@
 #ifdef __APPLE__
     #include <sys/types.h>
 #endif
-
+#if defined(__FreeBSD__)
+#include <time.h>
+#endif

 #ifndef __BEGIN_DECLS
 #define __BEGIN_DECLS

These changes are small but could be very useful for FreeBSD community :-)

Thanks a lot for your work.

Greetings,
--
krzyszstofs

**Comment by roehling** [comment]
Thank you very much. I'll add the includes for those header files.
