### ISSUE TITLE
postsrsd lacks dual stack support

### ISSUE THREAD

**Issue by quanah** [roehling/postsrsd#46]
On systems where both ipv4 and ipv6 are configured, postsrsd only listens on IPv4:

root@zre-ldap002:/opt/zimbra/common# netstat -an | grep 10001
tcp        0      0 127.0.0.1:10001         0.0.0.0:*               LISTEN
root@zre-ldap002:/opt/zimbra/common# netstat -an | grep 10002
tcp        0      0 127.0.0.1:10002         0.0.0.0:*               LISTEN

If IPv6 is also available, it should listen on it as well, unless -4 was passed as an option.  Likewise, the reverse if -6 was passed as an option, it should only listen on the ipv6 addr and not the ipv4 addr.

**Comment by roehling** [comment]
Since the daemon is supposed to listen to loopback only, I don't think we really need dual stack support. In fact, the only reason I added IPv6 support in the first place was to ensure that the daemon can run on IPv6-only hosts.

**Comment by quanah** [comment]
I disagree. ;) The OS may prefer to attempt connecting to the ipv6 addr over the ipv4 addr when supporting both ipv4 & ipv6, so listening on ipv6 can save a few milliseconds every time a new connection is opened, which adds up over time.   Particularly if setting something like: tcp:localhost:10001

**Comment by bjoe2k4** [comment]
Quick solution if you really wanna have dualstack right now: modify the start script to start postsrsd twice (or duplicate the init script). The overhead is really minimal.

On the other hand a typical latency of an email messages is in the order of seconds to minutes (depending on the antispam mechanisms) and i don't think a few microseconds matter in this case.

**Comment by quanah** [comment]
My use case is probably not the same as most peoples.  I'm working at integrating postSRSd into our product, which is used by clients who may have 10 users or 150 million + users.  Efficiency matters significantly in this case.  So does the ability to easily automate the installation and configuration, and to honor what the client specifies as to how they want things to behave (ipv4 only, dual, or ipv6 only).  Then there are other issues, such as the broken version of netcat shipped in RHEL7, which if you're using it to test ports being alive, doesn't work right if it an interface has both ipv6 and ipv4 enabled, because it won't fail over to the ipv4 address.  So in this case, if I were to try and validate a response from postsrsd, it would fail on rhel7 with 127.0.0.1 and ::1 being active.

**Comment by roehling** [comment]
I will see what I can do. Thankfully, Postfix keeps the TCP connection alive (and PostSRSd supports that), so the actual connection overhead is almost nonexistent on a busy system.

**Comment by quanah** [comment]
Thanks, I appreciate it!
