### ISSUE TITLE
check for reverse srs forgery?

### ISSUE THREAD

**Issue by xahare** [roehling/postsrsd#47]
how can we check for reverse srs forgery? can you give an example as a milter or sa rule?

**Comment by roehling** [comment]
I have no idea why you want a milter or SpamAssassin rule. If the signature is invalid, the address won't be accepted and an error message is logged in `/var/log/mail.log`. Note that the signature is a HMAC digest, so you cannot verify it without knowing the secret. And I would strongly advised against leaking the secret to any other program.

**Comment by xahare** [comment]
sweet! its already done! i just misunderstood. thanks!
