### ISSUE TITLE
PostSRS failing to start

### ISSUE THREAD

**Issue by dancrumb** [roehling/postsrsd#49]
I installed PostSRS per the directions in the README and am getting:

```
# service postsrsd start
Failed to start postsrsd.service: Unit postsrsd.service failed to load: No such file or directory.
```

I'm using 
```
# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

I built with

```
# cmake -DINIT_FLAVOR=upstart ../
# make
# make install
```

Any idea why the install is not work?

**Comment by dancrumb** [comment]
FWIW, I installed via your PPA and that worked just fine!

**Comment by emibcn** [comment]
@dancrumb : which PPA?

**Comment by roehling** [comment]
I'm not using Ubuntu 15.10 myself, but AFAIK they switched from upstart to systemd.

**Comment by dancrumb** [comment]
@emibcn I used this one: https://launchpad.net/~roehling/+archive/ubuntu/latest

**Comment by emibcn** [comment]
Thanks!

**Comment by roehling** [comment]
I believe that the `-DINIT_FLAVOR=upstart` above is the culprit. The README file is outdated and does not mention systemd yet.

**Comment by zubfatal** [comment]
I realise this issue is already closed, but don't know where else to put this info.
I had the same service error message on Debian 8 and was able to resolve it by simply doing:

**Comment by lgleim** [comment]
> `systemctl enable postsrsd`
Solved the problem for me on Debian 8. This should likely be included in the Readme...
