### ISSUE TITLE
vacation response problem

### ISSUE THREAD

**Issue by fisher006** [roehling/postsrsd#53]
Hi, I have sieve + dovecot + postfix with postsrsd but:

if i send e-mail to account with vacation response I had bad headers.

> From: test@domain.tld
> To:SRS0=mQhw=PU=domain.tld=test@domain.tld

i need change to: 

From: test@domain.tld
To: account@domain.tld

this is postfix logs:

Mar 24 19:30:32 mail3 postsrsd[1577]: srs_reverse: <srs0=mqhw=pu=domain.tld=test@domain.tld> rewritten as test@domain.tld
Mar 24 19:30:32 mail3 postsrsd[1520]: srs_forward: <""> not rewritten: No at sign in sender address
Mar 24 19:30:32 mail3 postsrsd[1578]: srs_reverse: <SRS0=mQhw=PU=domain.tld=test@domain.tld> rewritten as test@domain.tld
Mar 24 19:30:32 mail3 postfix/cleanup[1518]: D5F73809093F: message-id=dovecot-sieve-1458844210-716979-0@domain.tld
Mar 24 19:30:32 mail3 postfix/qmgr[1421]: D5F73809093F: from=<>, size=847, nrcpt=1 (queue active)
Mar 24 19:30:38 mail3 postfix/smtp[1579]: D5F73809093F: to=test@domain.tld, orig_to=<SRS0=mQhw=PU=domain.tld@domain.tld>, delay=5.3, delays=0.06/0.02/0.13/5.1, dsn=2.0.0, status=sent (250 OK id=1ajA1L-0008A1-1B)
Mar 24 19:30:38 mail3 postfix/qmgr[1421]: D5F73809093F: removed

Any sugesstions?

**Comment by roehling** [comment]
This doesn't look like a PostSRSd issue to me. Have you verified that the vacation response works without it?

**Comment by fisher006** [comment]
Yes without works fine.
With postsrsd vacation response was be delivered but have bad "to"

`From: test@domain.tld
To:SRS0=mQhw=PU=domain.tld=test@domain.tld

i need change to:

From: test@domain.tld
To: account@domain.tld`


here is correct log:

`Mar 24 19:30:32 mail3 postsrsd[1577]: srs_reverse: <srs0=mqhw=pu=domain.tld=test@domain.tld> rewritten as <test@domain.tld>
Mar 24 19:30:32 mail3 postsrsd[1520]: srs_forward: <""> not rewritten: No at sign in sender address
Mar 24 19:30:32 mail3 postsrsd[1578]: srs_reverse: <SRS0=mQhw=PU=domain.tld=test@domain.tld> rewritten as <test@domain.tld>
Mar 24 19:30:32 mail3 postfix/cleanup[1518]: D5F73809093F: message-id=<dovecot-sieve-1458844210-716979-0@storage-s14.domain.tld>
Mar 24 19:30:32 mail3 postfix/qmgr[1421]: D5F73809093F: from=<>, size=847, nrcpt=1 (queue active)
Mar 24 19:30:38 mail3 postfix/smtp[1579]: D5F73809093F: to=<test@domain.tld>, orig_to=<SRS0=mQhw=PU=domain.tld=test@domain.tld>, relay=mx4.domain.tld[193.187.65.55]:587, delay=5.3, delays=0.06/0.02/0.13/5.1, dsn=2.0.0, status=sent (250 OK id=1ajA1L-0008A1-1B)
Mar 24 19:30:38 mail3 postfix/qmgr[1421]: D5F73809093F: removed`

**Comment by roehling** [comment]
Since account@domain.ltd does not show up anywhere in your log snippet, I can't tell where it went wrong. If you want me to do your work for you, you should at least show me the complete transaction, and not just the last few lines.

**Comment by fisher006** [comment]
this is full log incoming and outgoing ( vacation ) message.
http://pastebin.com/UZfU3KZJ

vacation message header:

http://i68.tinypic.com/24pa32o.jpg

**Comment by roehling** [comment]
The mail in question comes with empty envelope sender, which is usually done for delivery status notifications. My guess is that there's an attempt to deliver a vacation response before, and it fails for some reason in a way that prompts Postfix to send a DSN. You're just looking at that DSN here and not the actual error condition that happened before.

**Comment by fisher006** [comment]
Maybe You have any advice how resolve this problem?

**Comment by roehling** [comment]
Closing this issue, since it seems to be stale. Feel free to reopen.
