### ISSUE TITLE
incorrect srs rewrite?

### ISSUE THREAD

**Issue by dndlion** [roehling/postsrsd#54]
According to my postfix log all the rewrites don't look quite right - e.g.:

`Mar 29 20:56:14 something postsrsd[1442]: srs_forward: <ossecmnew@something.net> rewritten as <SRS0=uIZh=PZ=something.net=ossecmnew@net>`

i.e. the domain name is not appearing at the end of the rewrite - just the tld (which is correct) - any ideas why this would be?

**Comment by roehling** [comment]
Have you set the domain name in `/etc/default/postsrsd`? If not, have you verified that `postconf -h mydomain` returns the correct domain name?

**Comment by dndlion** [comment]
It seems mydomain was returning: net - I've set it and all is working.  I didn't/don't have it set in `/etc/default/postsrsd`.  Thanks for your help!
