### ISSUE TITLE
Policy CMP0026 is not set, Failed to start postsrsd.service

### ISSUE THREAD

**Issue by hgisoeura** [roehling/postsrsd#55]
When running make on a Raspberry Pi 3 Jessie following warning occurs:

> CMake Warning (dev) at CMakeLists.txt:85 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
  The LOCATION property should not be read from target "postsrsd".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.
  This warning is for project developers.  Use -Wno-dev to suppress it.

I ignored this warning an continued
`sudo make install`
and 
`sudo service postsrsd start`
which gave me

> Failed to start postsrsd.service: Unit postsrsd.service failed to load: No such file or directory.

I must be doing something wrong or overlook something here?

**Comment by roehling** [comment]
Did the init system autodetect work properly? You can try to rebuild using `sudo make install INIT_FLAVOR=systemd`

**Comment by hgisoeura** [comment]
Thanks, that solved it all. The init system auto-detect was "tricked" into using sysv-lsb because a tutorial I found on the internet wrongly advised to install sysv-rc in the first place...

**Comment by n3storm** [comment]
Debian Jessie (systemd) here. I still do not understand your solution. I have `cmake_policy given unknown first argument "CMP0026"` error while doing **make**.

Cloned repo today. Git pull on a Debian wheezy today and updated with no problem.

**Comment by roehling** [comment]
Oh yes, I forgot the "SET" argument. 

The `cmake_policy()` command has nothing to do with the problem here, it's just a warning emitted by CMake 3.0.2, and I'm just trying to get rid of it to not confuse people.
