### ISSUE TITLE
CentOS 6 init error

### ISSUE THREAD

**Issue by tomsommer** [roehling/postsrsd#56]
```
/etc/init.d/postsrsd: line 13: syntax error near unexpected token `newline'
/etc/init.d/postsrsd: line 13: `DAEMON=/usr/local/sbin/$<TARGET_FILE_NAME:postsrsd>'
```

**Comment by roehling** [comment]
It seems that CMake 2.6 does not support generator expressions. :-(
It's the latest commit that breaks this. You can  `git checkout HEAD^` for now until I have time to author a proper fix later today.
