### ISSUE TITLE
Manual install instructions

### ISSUE THREAD

**Issue by SimonHobson** [roehling/postsrsd#57]
Are there any manual install instructions - other than deciphering the makefile ? In particular, the format of the secrets file.
Reason ?
I have several systems to put this on, which don't have any build packages installed. So I'll be building on another system and then copying the files across.

Of course, if the package found it's way into Wheezy backports that would be even better, but I'm not greedy :-)

**Comment by roehling** [comment]
For the format of the screts file, see the Configuration section in the README: It's a text file where each line is taken as secret key for the signature algorithm. The first line is used to sign and verify, the following lines for verification only (which can be used to transition to a new secret).

A simple way to find out which files are installed is `make install DESTDIR=/tmp/postsrsd` and then examine the files and folders below `/tmp/postsrsd`.

**Comment by SimonHobson** [comment]
Thanks for that - certainly easier than manually figuring out what goes where.
Could I suggest some additions/changes to the docs ?
Yes, the readme file does say that the first line is used as a key - but gives no indication what should be in it - does length matter ? does character set matter ? I see from the makefile that you've taken 18 bytes from urandom and base64 encoded them. The purpose of additional lines (managing a key change) had eluded me.

**Comment by roehling** [comment]
The key is a free-form secret string. I take 18 bytes from urandom because I'm aiming for about 128 bits of entropy. The base64 encode ensures that the string ends up with printable characters only.

**Comment by roehling** [comment]
Closing this issue, since it seems to be stale. Feel free to reopen.
