### ISSUE TITLE
Enhancement request: Add Postfix queue ID to logging

### ISSUE THREAD

**Issue by SimonHobson** [roehling/postsrsd#60]
Is the Postfix (or other mailer) Queue ID available to postsrsd ? If so, can it be included in the log ?
On a single quiet server it's not an issue, but once there's multiple servers and/or things get even mildly busy, the logs are impossible to read without thinning them out (eg with grep).
A typical workflow for me when dealing with a user "query" is to grep for what information is known (eg sender, recipient, approx time), then find the queue ID that seems to be the message best fitting the user supplied information, and then grep for that ID to find how the message passed through the system. As the queue ID isn't in the postsrsd logging, it doesn't appear in this last step.

**Comment by roehling** [comment]
Unfortunately, the queue ID is not available. PostSRSd merely rewrites email addresses and has no access to any routing information nor any internal Postfix states.
