### ISSUE TITLE
postsrsd threads

### ISSUE THREAD

**Issue by christianreiss** [roehling/postsrsd#61]
Hey folks!

I am running postsrsd and I noticed that on some servers the binary seems to spawn child procs:

`├─postsrsd───7*[postsrsd]`

(pstree output) - on some other system it does not behave like this. Is this normal? When does the daemon spawn childs?

Cheers,
Chris.

**Comment by roehling** [comment]
Yes, this is normal. The daemon forks children to handle incoming requests, and TCP connections are kept alive by Postfix and PostSRSd to minimize the connection overhead on busy servers. By default, PostSRSd will terminate idle connections after 30 minutes of inactivity.

**Comment by christianreiss** [comment]
Hey Tim,

thanks for a swift and precise answer. Now my mind is at ease :)

-Chris.
