### ISSUE TITLE
Performance / Scaling Issue

### ISSUE THREAD

**Issue by WanTanFao** [roehling/postsrsd#62]
Hi,

not really an issue for you to fix but probably related to the "Known Issues" in the README: since PostSRSD handles rewriting apparently before verifying if a mail is to be accepted by postfix at all, we run into major performance bottlenecks through rewriting for anny SMTP connection. We've implemented your software on some forwarding nodes and they handle around 100k legitimate mails in 24 hours. The number of illegitimate connections is a lot higher, but rewrites are done whatsoever resulting in really poor processing performance and high CPU load.

Do you have any suggestions how to overcome this? The delays in transmission are pretty high already and we don't want to disable SRS at this point as it's quite effective.

Best
Fabian

**Comment by roehling** [comment]
Apart from the usual tricks (e.g. running postscreen or a second instance of Postfix to filter spam before handing it over to the rewriting instance), I'd say the majority of computing happens in the HMAC-SHA1 functions. The source files I copied from SRS2 have the option to use OpenSSL, which may or may not run faster than their own code. Define the `USE_OPENSSL` macro at the top of `srs2.c`, and add a line `target_link_libraries(${PROJECT_NAME} ssl crypto)` after the `add_executable` line in `CMakeLists.txt`.

I suggest writing a small test program that connects to TCP port 10001 and measures how often you can write 'get address@example.com' to the socket and read the rewritten reply in a given time slot (e.g. 10 seconds). If you do find a significant difference, please share the results with me.

**Comment by roehling** [comment]
Closing this issue, since it seems to be stale. Feel free to reopen.
