### ISSUE TITLE
SRS_DOMAIN defaults to hostname after removing first sub-domain name...

### ISSUE THREAD

**Issue by AlexisWilke** [roehling/postsrsd#66]
I have a computer which I name "m2osw.com" so that way it gets its PTR as "m2osw.com" (that's how DigitalOcean works, at least so it seems.) I also tried to name my mail computers with "mail.m2osw.com", but I have not (yet) been able to get gmail, yahoo!, etc. to accept such along with SPIF, DMARC, etc. Anyway...

This means my `/etc/hostname` file is just "m2osw.com".

When I do not specifically setup the `SRS_DOMAIN` variable, the result is that `postsrsd` uses "com" instead of "m2osw.com".

I would think that you should not remove the sub-domain name if there is a single dot in the name. Also there are ways to [determine whether a name is an official TLD](http://snapwebsites.org/project/libtld) and you could use that technique to clearly only remove sub-domain names and not the actual domain name. I know you also have to deal with names such as "localhost", although really those won't work on the Internet and thus can most certainly be ignored in your case.

Without setting up SRS_DOMAIN, I would get errors when forwarding emails because my archive server would receive emails with names such as `SRS...@com`. The "@com" would be refused by the recipient, obviously.

Reference: http://serverfault.com/questions/829210/postfix-gives-me-sender-address-rejected-need-fully-qualified-address-errors

**Comment by roehling** [comment]
The PostSRSd auto-detect uses the `$mydomain` postfix configuration setting, i.e. the output of `postconf -h mydomain`. The default is the hostname minus the first component, so you should probably set this up explicitly in your `main.cf`.

**Comment by AlexisWilke** [comment]
In `/etc/postfix/main.cf` I have

    myhostname = m2osw.com

And in `myorigin` I have a filename:

    myorigin = /etc/mailname

Which includes the same domain: `m2osw.com`.

When we try to use `mail.m2osw.com`, we have many other  problems with DKIM and SPIF... So I'm not too sure how we could change `m2osw.com` to anything else.

**Comment by roehling** [comment]
If you want to use `myhostname` this way, you must also set `mydomain = m2osw.com`. Then everything is fine.
