### ISSUE TITLE
Can this be used to rewrite the "From:" header?

### ISSUE THREAD

**Issue by WesCossick** [roehling/postsrsd#67]
With stricter DMARC settings becoming more prevalent (AOL & Yahoo), it's not enough for a forwarding server to simply change the envelope from to pass SPF tests. Now, the from address that users see must also be aligned with the envelope from and DKIM domain. Otherwise, forwarded messages will often be rejected outright.

Knowing this, is it possible to use PostSRSd to rewrite the "From:" header?

**Comment by roehling** [comment]
You can rewrite the From: header by adding the the `header_sender` option to `sender_canonical_classes`. However, this will break email clients, since replies will go the SRS-rewritten address. DMARC pretty much breaks email forwarding for good...

**Comment by WesCossick** [comment]
Just in case anyone else was wondering, I was able to work around the DMARC problem by writing my own script to rewrite the "from" address to a domain under our control, then add a "reply-to" header with the original "from" address.

**Comment by ck-ws** [comment]
Would you mind sharing this script? Or at least how you realized it?

**Comment by roehling** [comment]
@WesCossick if you are willing to contribute, I will gladly add your script to PostSRSd.

**Comment by WesCossick** [comment]
I wrote a PHP script that handled it, because that's the language I'm most familiar with and I needed a solution quickly. As such, it's probably not the best fit for PostSRSd (or the most efficient possible solution).

I may write a blog article on how it works in the future. If I do, I'll reference it here.

**Comment by joostrijneveld** [comment]
@WesCossick Did you ever end up writing this down somewhere?

**Comment by WesCossick** [comment]
@joostrijneveld We're still using an implementation of what I wrote, but I haven't yet written an article about it on our company blog... I'd like to, but we're swamped right now. It's on my list of things to get done eventually though.

**Comment by urc** [comment]
Would you mind at least sharing a rough outline of where this script sits in the overall message flow? We're running into the same problem, figured we'd need a similar solution, and I'd rather avoid reinventing the wheel. Thanks!

**Comment by WesCossick** [comment]
@urc We added the following lines to the bottom of Postfix's `master.cf` file:

```
process-outgoing unix - n n - - pipe
    flags=FR user=www-data argv=/path/to/your/script ${sender} ${recipient}
```

**Comment by urc** [comment]
@WesCossick Ah, that's pretty much what I had arrived at, except that we're looking at implementing it as a policy daemon. Thanks! :)

**Comment by npsimons** [comment]
> Just in case anyone else was wondering, I was able to work around the DMARC problem by writing my own script to rewrite the "from" address to a domain under our control, then add a "reply-to" header with the original "from" address.

This is precisely what I was looking for when I landed on this page from Google; got a snippet? This is, IMHO, as close to ideal as my limited imagination can come up with.

**Comment by frugan-it** [comment]
My 2 cents..

**/etc/postfix/main.cf**

```cfg
smtp_header_checks = pcre:/etc/postfix/smtp_header_checks.pcre
```

**/etc/postfix/smtp_header_checks.pcre**

```cfg
/^From: .*@(yahoo.com|rocketmail.com|ymail.com|y7mail.com|yahoo.at|yahoo.be|yahoo.bg|yahoo.cl|yahoo.co.hu|yahoo.co.id|yahoo.co.il|yahoo.co.kr|yahoo.co.th|yahoo.co.za|yahoo.com.co|yahoo.com.hr|yahoo.com.my|yahoo.com.pe|yahoo.com.ph|yahoo.com.sg|yahoo.com.tr|yahoo.com.tw|yahoo.com.ua|yahoo.com.ve|yahoo.com.vn|yahoo.cz|yahoo.dk|yahoo.ee|yahoo.fi|yahoo.hr|yahoo.hu|yahoo.ie|yahoo.lt|yahoo.lv|yahoo.nl|yahoo.no|yahoo.pl|yahoo.pt|yahoo.rs|yahoo.se|yahoo.si|yahoo.sk|yahoogroups.co.kr|yahoogroups.com.cn|yahoogroups.com.sg|yahoogroups.com.tw|yahoogrupper.dk|yahoogruppi.it|yahooxtra.co.nz|yahoo.ca|yahoo.co.in|yahoo.co.nz|yahoo.co.uk|yahoo.com.ar|yahoo.com.au|yahoo.com.br|yahoo.com.hk|yahoo.com.mx|yahoo.de|yahoo.es|yahoo.fr|yahoo.gr|yahoo.in|yahoo.it|yahoo.ro)$/ REPLACE From: noreply@domain.tld
```

The only problem I encounter with this method is that the "Reply-To" header is not added.
Do you find other drawbacks in using this simple method?

**Comment by frugan-it** [comment]
This comment https://stackoverflow.com/a/63024268/3929620 seems to have pointed me in the right direction regarding adding the Reply-To header.


**/etc/postfix/main.cf**

```cfg
header_checks = pcre:/etc/postfix/header_checks.pcre
smtp_header_checks = pcre:/etc/postfix/smtp_header_checks.pcre
```

**/etc/postfix/header_checks.pcre**

```
if !/^Reply-To: .*/
/^From: (.*@(yahoo.com|rocketmail.com|ymail.com|y7mail.com|yahoo.at|yahoo.be|yahoo.bg|yahoo.cl|yahoo.co.hu|yahoo.co.id|yahoo.co.il|yahoo.co.kr|yahoo.co.th|yahoo.co.za|yahoo.com.co|yahoo.com.hr|yahoo.com.my|yahoo.com.pe|yahoo.com.ph|yahoo.com.sg|yahoo.com.tr|yahoo.com.tw|yahoo.com.ua|yahoo.com.ve|yahoo.com.vn|yahoo.cz|yahoo.dk|yahoo.ee|yahoo.fi|yahoo.hr|yahoo.hu|yahoo.ie|yahoo.lt|yahoo.lv|yahoo.nl|yahoo.no|yahoo.pl|yahoo.pt|yahoo.rs|yahoo.se|yahoo.si|yahoo.sk|yahoogroups.co.kr|yahoogroups.com.cn|yahoogroups.com.sg|yahoogroups.com.tw|yahoogrupper.dk|yahoogruppi.it|yahooxtra.co.nz|yahoo.ca|yahoo.co.in|yahoo.co.nz|yahoo.co.uk|yahoo.com.ar|yahoo.com.au|yahoo.com.br|yahoo.com.hk|yahoo.com.mx|yahoo.de|yahoo.es|yahoo.fr|yahoo.gr|yahoo.in|yahoo.it|yahoo.ro)\>?)$/
    PREPEND Reply-To: $1
endif
```

**/etc/postfix/smtp_header_checks.pcre**

```
/^From: .*@(yahoo.com|rocketmail.com|ymail.com|y7mail.com|yahoo.at|yahoo.be|yahoo.bg|yahoo.cl|yahoo.co.hu|yahoo.co.id|yahoo.co.il|yahoo.co.kr|yahoo.co.th|yahoo.co.za|yahoo.com.co|yahoo.com.hr|yahoo.com.my|yahoo.com.pe|yahoo.com.ph|yahoo.com.sg|yahoo.com.tr|yahoo.com.tw|yahoo.com.ua|yahoo.com.ve|yahoo.com.vn|yahoo.cz|yahoo.dk|yahoo.ee|yahoo.fi|yahoo.hr|yahoo.hu|yahoo.ie|yahoo.lt|yahoo.lv|yahoo.nl|yahoo.no|yahoo.pl|yahoo.pt|yahoo.rs|yahoo.se|yahoo.si|yahoo.sk|yahoogroups.co.kr|yahoogroups.com.cn|yahoogroups.com.sg|yahoogroups.com.tw|yahoogrupper.dk|yahoogruppi.it|yahooxtra.co.nz|yahoo.ca|yahoo.co.in|yahoo.co.nz|yahoo.co.uk|yahoo.com.ar|yahoo.com.au|yahoo.com.br|yahoo.com.hk|yahoo.com.mx|yahoo.de|yahoo.es|yahoo.fr|yahoo.gr|yahoo.in|yahoo.it|yahoo.ro)\>?$/
    REPLACE From: noreply@domain.tld
```

I'd be curious to hear your feedback..
