### ISSUE TITLE
Install warnings on Ubuntu 18

### ISSUE THREAD

**Issue by billynoah** [roehling/postsrsd#83]
Getting the following installing via `apt-get install postsrsd` on Ubuntu 18 - looks harmless enough and postsrsd appears to be working, but just thought I'd check in to find out why.
```
Setting up postsrsd (1.4-1) ...
postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_sender_restrictions
postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_client_restrictions
postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_helo_restrictions
postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_sender_restrictions
postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_client_restrictions
postconf: warning: /etc/postfix/master.cf: undefined parameter: mua_helo_restrictions
```

**Comment by bjoe2k4** [comment]
seems unrelated to postsrsd

**Comment by roehling** [comment]
Agreed. As a matter of fact, Postfix has no `mua_*_restrictions` parameters at all. The only mention I found was in a half-broken tutorial on how to setup Postfix.

By the way, I cannot stress enough how bad of an idea it is to blindly use Postfix parameters without properly understanding what they're doing. Please, for the sake of everyone else on the Internet, take the time to understand what you're doing before you unleash your mail server upon the world. :-/

**Comment by billynoah** [comment]
Ah.. I see now these are in fact undefined variables already present in master.cf.

@roehling - your "before you unleash your mailserver upon the world" comment implies that I messed something up here.  For the record this is the [*default master.cf file*](http://archive.ubuntu.com/ubuntu/pool/main/p/postfix/postfix_3.3.0.orig.tar.gz) that ships with Ubuntu 18.  I had not made any changes to it.  Not sure what the package maintainer had in mind here, but just want to make it clear that the presence of these parameters are not due to any tinkering on our side.

**Comment by roehling** [comment]
I'm sorry, in hindsight my words might be a bit harsher than appropriate. I did indeed (wrongly) assume that those variables were the result of some thinkering.

Maybe you should file a bug with Ubuntu? Not sure what they are trying to achieve here, either, besides creating unnecessary noise in the system log.

**Comment by billynoah** [comment]
That's understandable - I'll do a bit more looking into it and maybe file a bug.  If you want to remove this ticket feel free - I agree it's unrelated.  And thanks for your work on postsrsd!
