### ISSUE TITLE
[Bug] Wrong systemd daemon generation

### ISSUE THREAD

**Issue by tairosonloa** [roehling/postsrsd#88]
Hi!

I'm here with a bug report. I installed postsrsd following the readme of the repository, and the file `/etc/systemd/system/postsrsd.service` which was auto-generated had a syntax error which prevents it to start.

Auto-generated daemon was:
`ExecStart=/usr/local/sbin/ -f [...]`

Changed it to:
`ExecStart=/usr/local/sbin/postsrsd -f [...]`

Did `systemctl daemon-reload` and `systemctl start postsrsd.service` and now everything is working!

Edit: I'm on Debian 9

**Comment by roehling** [comment]
Oops, that's a regression caused by a134b270f5050e25f51099511e1afed96214c35c, when I tried to get rid of an outdated CMake feature.
