### ISSUE TITLE
Newly introduced systemd detection does not work

### ISSUE THREAD

**Issue by bertptrs** [roehling/postsrsd#91]
In 8df0c1f4b2ffbab763de89d8bc62057b505206e6 the detection of systemd-based systems was changed to seeing whether the program `systemd` can be found. However, on most systems, this program is not actually part of systemd, at least not on ArchLinux. It now incorrectly assumes there is no init system, where there clearly is.

A more appropriate check (if you don't want to return to the old behaviour) is to do the same check for the `systemctl` binary. That one is unique to systemd systems (at least as far as I know) and should always be on the path.

**Comment by roehling** [comment]
The old check failed on my Ubuntu 18.04 LTS system, so I implemented your suggestion. Thank you for the bug report!
