### ISSUE TITLE
init script does not properly stop postsrsd on Debian Buster

### ISSUE THREAD

**Issue by urc** [roehling/postsrsd#93]
Something in the sysv version of the init script seems to prevent postsrsd from properly stopping with the version of 'start-stop-daemon' that ships with Debian Buster, leading to multiple running copies.

The fix seems to be to add `--exec $DAEMON` to the invocation used in the 'stop' action, as detailed in this particular Debian issue;

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922395

**Comment by roehling** [comment]
I added the fix as you suggested, but this will not automatically propagate to Debian. If this is an issue with Debian, you should file a bug with them instead.

**Comment by urc** [comment]
Ah, thanks :)  Figured I'd see if I could get it fixed upstream first, since that tends to make it easier on the maintainer, and thus faster to get a fix in.

**Comment by oxan** [comment]
Ah, unfortunately I didn't see this until now (feel free to @-mention me on Debian-related issues in the future). I've backported the fix to the 1.6 package, which will appear in the archives shortly.
