### ISSUE TITLE
Option to use unix sockets instead of TCP

### ISSUE THREAD

**Issue by clarfonthey** [roehling/postsrsd#96]
Would be nice to have.

Envisioning this as something like a `-u` flag where the host is recognised as a directory, and the ports are recognised as files in that directory.

**Comment by roehling** [comment]
I like this idea, as Postfix added support for `socketmap` lookups a while ago. It's probably not gonna happen until version 2.0 though, as this is a pretty substantial change, both in the internal logic and the way PostSRSd is integrated with Postfix.

**Comment by jeredfloyd** [comment]
PR #123 should enable this for the sender rewriting workflow, at least.

**Comment by roehling** [comment]
https://github.com/roehling/postsrsd/releases/tag/2.0.0a1
