### ISSUE TITLE
SPF should ignore Reply-To

### ISSUE THREAD

**Issue by Yajo** [roehling/postsrsd#99]
Hello everyone.

First of all, thanks for this wonderful project!

I'm having an issue that you can (please do) read in https://github.com/tomav/docker-mailserver/issues/1350#issue-544192173.

tl;dr: SPF affects the `Reply-To` header, and there's nothing I can do to avoid that.

I think this is a problem because then some apps that act as message brokers through emails cannot work 100% fine.

Any help on the subject please? Thanks!

**Comment by roehling** [comment]
I replied directly to the issue above. Hope that it helps.
